Update TranscodingTask.php
Updated the AddStitchVideoItem to not check explicitly for undefined but instead use the isset() method. Newer versions of PHP will throw the following error when checking for undefined.

ErrorException: Use of undefined constant undefined - assumed 'undefined' (this will throw an Error in a future version of PHP)